POST http://localhost:3003/user/signup
constent-type : application/json

{
	"name": "Michael Scott",
	"email": "michael@dundermifflin.com",
	"password": "theboss",
	"role": "ADMIN"
}


###


GET http://localhost:3003/all
constent-type : application/signup

Authorization: "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNjgzZTkxLWY1ODMtNDE4ZS04NzRhLWNjNzYzYjZhYThkYSIsImlhdCI6MTU5NzAyNDA4NCwiZXhwIjoxNjI4NTgxNjg0fQ.l6s8rKz1g_qS1uOJWSibWcGhDn-DbO7mWPEPGpLJ01Y"
