POST http://localhost:3003/user
Content-Type: application/json

	{
		"name" : "Jangasd",
		"email" : "jangasd@gmail.com",
		"password" : "123456",
    "role": "NORMAL"
	}

###

POST http://localhost:3003/user/login